.\"                                      Hey, EMACS: -*- nroff -*-
.TH REMINDERER 1 "November 22, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
reminderer \- reminds about upcoming events or things to do.
.SH SYNOPSIS
.B reminderer
.RI [-n]
.SH DESCRIPTION
Reminderer is a simple GTK+ program to remind about upcoming events. Allows
also to define a "to do" list.
.SH OPTIONS
.TP
.B \-n
Exit immediately when reminders list is empty.
.SH AUTHOR
reminderer was written by Rafal Dabrowa <fatwildcat@gmail.com>
